# Generated by Django 3.1.3 on 2020-12-08 22:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pythons_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='python',
            name='image',
            field=models.ImageField(upload_to='pythons/'),
        ),
        migrations.AlterField(
            model_name='python',
            name='wishes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
