# Generated by Django 3.1.3 on 2020-12-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythons_app', '0002_auto_20201209_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='python',
            name='image',
            field=models.URLField(),
        ),
    ]
